export {
  isAuthenticated,
  authenticateDrive,
  performOAuthFlow,
  setOAuthServerUrl,
  getOAuthServerUrl,
  isOAuthServerConfigured,
  getDriveClient,
  isDriveConnected,
  disconnectDrive,
  logout,
  uploadFile,
  downloadFile,
  deleteFile,
  listFiles,
  createFolder,
  findFolder,
  getOrCreateFolder,
  // Hidden appDataFolder functions
  uploadToAppData,
  uploadBufferToAppData,
  listAppDataFiles,
  findAppDataFile,
  downloadFromAppData,
  downloadAppDataToBuffer,
  deleteFromAppData,
  updateAppDataFile,
  getOrCreateVaultIndex,
  hasAppDataAccess,
} from './driveClient.js';

export {
  getSlasshyFolder,
  uploadEntry,
  downloadEntry,
  deleteEntryFromDrive,
  syncWithDrive,
  getSyncStatus,
} from './synchronizer.js';

export {
  uploadFileToCloud,
  downloadFileFromCloud,
  deleteFileFromCloud,
  isFileInCloud,
  getCloudStorageUsage,
  isCloudSyncAvailable,
  streamDownloadToFile,
  getParallelismInfo,
  type CloudFileChunk,
  type CloudFileInfo,
} from './fileSyncService.js';
