export {
  vaultExists,
  initVaultWithHeader as initVault,
  unlock,
  lock,
  isUnlocked,
  addEntry,
  addFileEntry,
  addNoteEntry,
  getEntry,
  getFileEntry,
  getNoteEntry,
  getFileData,
  searchEntries,
  listEntries,
  updateEntry,
  updateNoteEntry,
  deleteEntry,
  toggleFavorite,
  getStats,
  getVaultPaths,
  getVaultIndex,
  updateVaultIndex,
  getTempFilesDir,
  cleanupTempFiles,
  getVault2FAConfig,
  isVault2FAEnabled,
  setVault2FAConfig,
  useBackupCode,
} from './vaultManager.js';

export {
  createEntry,
  createFileEntry,
  createNoteEntry,
  validateEntry,
  validateFileEntry,
  validateNoteEntry,
  validateVaultIndex,
  type Entry,
  type FileEntry,
  type NoteEntry,
  type VaultIndex,
  type IndexEntry,
  type VaultConfig,
  type EntryTypeEnum,
  type Vault2FAConfig,
} from './schema.js';
