export {
  vaultExists,
  initVaultWithHeader as initVault,
  unlock,
  lock,
  isUnlocked,
  addEntry,
  addFileEntry,
  getEntry,
  getFileEntry,
  getFileData,
  searchEntries,
  listEntries,
  updateEntry,
  deleteEntry,
  getStats,
  getVaultPaths,
  getVaultIndex,
  updateVaultIndex,
  getTempFilesDir,
  cleanupTempFiles,
} from './vaultManager.js';

export {
  createEntry,
  createFileEntry,
  validateEntry,
  validateFileEntry,
  validateVaultIndex,
  type Entry,
  type FileEntry,
  type VaultIndex,
  type IndexEntry,
  type VaultConfig,
  type EntryTypeEnum,
} from './schema.js';
